# Generated by Django 3.0.10 on 2020-11-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
        ('accounts', '0004_account_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='likes',
            field=models.ManyToManyField(blank=True, to='shows.Show'),
        ),
    ]
