# Generated by Django 3.0.10 on 2020-10-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_id', models.CharField(max_length=10)),
                ('is_movie', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=150)),
                ('director', models.CharField(max_length=120)),
                ('release_year', models.IntegerField()),
                ('rating', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
    ]
