# Generated by Django 3.0.10 on 2020-10-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flix', '0002_auto_20201010_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='category',
        ),
        migrations.AddField(
            model_name='show',
            name='category',
            field=models.ManyToManyField(to='flix.Category'),
        ),
        migrations.RemoveField(
            model_name='show',
            name='country',
        ),
        migrations.AddField(
            model_name='show',
            name='country',
            field=models.ManyToManyField(to='flix.Country'),
        ),
    ]
