# Generated by Django 3.0.10 on 2020-10-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flix', '0004_show_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='show',
            options={'ordering': ['title'], 'verbose_name_plural': 'Shows'},
        ),
        migrations.RemoveField(
            model_name='show',
            name='image',
        ),
        migrations.AddField(
            model_name='show',
            name='image_url',
            field=models.CharField(default='default_image.jpg', max_length=50),
        ),
    ]
