# Generated by Django 3.0.10 on 2020-11-10 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201110_1045'),
        ('flix', '0005_auto_20201019_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='category',
        ),
        migrations.RemoveField(
            model_name='show',
            name='country',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Show',
        ),
    ]
