# Generated by Django 3.0.10 on 2020-11-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='thumbnail_url',
            field=models.CharField(default='default_image.jpg', max_length=50),
        ),
    ]
